FactoryMachineSize=50
FactoryCarcaseSize=50
FactoryEngineSize=50
FactoryAccessorySize=50

AccessorySuppliers=3
Workers=3
Dealers=10

AccessorySupplierFrequency=5000
CarcaseSupplierFrequency=3000
EngineSupplierFrequency=3000
DealerFrequency=1000