DEFINE=calculator.command.Define
PUSH=calculator.command.Push
PRINT=calculator.command.Print
SQRT=calculator.command.Sqrt
DIV=calculator.command.Div
SUB=calculator.command.Sub
MUL=calculator.command.Mul
ADD=calculator.command.Add
